### PR TITLE
0.1.0 beta New login flow

### PR DESCRIPTION
**Pull request by fds2610**
pls test the new version

### CODE REVIEW

**Comment by e-alfred** [comment]
Do you have some binaries for testing?

**Comment by fds2610** [comment]
sure. i uploaded the beta to the standard bins. just take the links from README.md

**Comment by e-alfred** [comment]
On KDE/Debian 10, it seems like it doesn't open a browser window if I enter a Nextcloud hostname and click "send". It also shows "connecting..." all the time. On the command line it shows this:

```
Value: aHR0cHM6Ly9hZWdnZXIuYXRoLmN4Ojg5OTkvb3duY2xvdWQ=
connection
Value: aHR0cHM6Ly9hZWdnZXIuYXRoLmN4Ojg5OTkvb3duY2xvdWQ=
connection
Value: aHR0cHM6Ly9hZWdnZXIuYXRoLmN4Ojg5OTkvb3duY2xvdWQ=
connection
Value: aHR0cHM6Ly9hZWdnZXIuYXRoLmN4Ojg5OTkvb3duY2xvdWQ=
 ```

To have a truly independent client, wouldn't it be better to use the internal browser for displaying the Talk window and the login flow window?

**Comment by e-alfred** [comment]
On Windows the Login Flow window works, but I got some error messages while running the tray app:

image

**Comment by e-alfred** [comment]
On Windows the Login Flow window works, but I got some error messages while running the tray app:

image

**Comment by Refhi** [comment]
> To have a truly independent client, wouldn't it be better to use the internal browser for displaying the Talk window and the login flow window?

I must say I have a preference of using default web browser as it's more likely to already be properly configured (and already logged in on my nc session) and up to date. My own 2 cents.

Otherwise when trying to connect (Ubuntu Gnome LTS 20.04, NCT-desktop 0.1.0 => configure => hostname => validate => nothing happens
But when I use the cross to quit the window appears the flow login client (in electron browser) which works as expected (neat !)

**Comment by Baccanno** [comment]
Hi, Thanks you for your work 
I tried the App, 
I did configure > entered my url > Auth actually worked ! (Same way as described in the quote)
I then received a notification (no sound but visually red hint)
I double clicked the tray icon and it opened the electron window.

It would indeed be great to be able to configure the use of the default nav vs electron window especially during the beta period. The app does not work in the electron window on my system (win10)

image

> > To have a truly independent client, wouldn't it be better to use the internal browser for displaying the Talk window and the login flow window?
> 
> I must say I have a preference of using default web browser as it's more likely to already be properly configured (and already logged in on my nc session) and up to date. My own 2 cents.
> 
> Otherwise when trying to connect (Ubuntu Gnome LTS 20.04, NCT-desktop 0.1.0 => configure => hostname => validate => nothing happens
> But when I use the cross to quit the window appears the flow login client (in electron browser) which works as expected (neat !)

**Comment by fds2610** [comment]
hey dudes, thanks for your patien testing ;-) as i am new to github i just learn how to work with multiple branches, merges, conflicts and so on.
I just realized that i implemented to use the system's default browser in my main branch and i just did not update this branch for the new login flow with theese changes. fortunately you might not prefer all the same solution, so i fell back to the internal browser accidently having another issue being opened to re-implement your proposed new, future solution for configuring both options.
I will just upload all binaries again so after a couple of minute you should be able to download the new ones still being marked as 0.1.0. I will update this post as soon as uploading is done.

**Pull request merged**
